// Item catalogue — the equipment chapter of the 2024 D&D rules (Player's Handbook
// chapter 6, pp. 212-234). Parsed from the tables as they appear in the free Basic
// Rules (pp. 148-171), whose PDF is digital text rather than a scan:
// weights in pounds, values in copper pieces (1 GP = 100 CP, 1 SP = 10 CP, 1 EP = 50 CP,
// 1 PP = 1000 CP). Weight 0 means the book prints "—" for that item.
//
//   n = name, c = category, w = weight in lb, v = value in cp, d = details
//
// Magic items are deliberately absent: add them as custom items.

const CATEGORY_ORDER = [
  "Weapon · Simple Melee",
  "Weapon · Simple Ranged",
  "Weapon · Martial Melee",
  "Weapon · Martial Ranged",
  "Ammunition",
  "Armor · Light",
  "Armor · Medium",
  "Armor · Heavy",
  "Armor · Shield",
  "Adventuring Gear",
  "Equipment Pack",
  "Tools",
  "Spellcasting Focus",
  "Mount / Animal",
  "Tack & Vehicles",
];

const ITEMS = [
  // ---- Weapon · Simple Melee ----
  {n:"Club", c:"Weapon · Simple Melee", w:2, v:10, d:"1d4 Bludgeoning · Light · Mastery: Slow"},
  {n:"Dagger", c:"Weapon · Simple Melee", w:1, v:200, d:"1d4 Piercing · Finesse, Light, Thrown (Range 20/60) · Mastery: Nick"},
  {n:"Greatclub", c:"Weapon · Simple Melee", w:10, v:20, d:"1d8 Bludgeoning · Two-Handed · Mastery: Push"},
  {n:"Handaxe", c:"Weapon · Simple Melee", w:2, v:500, d:"1d6 Slashing · Light, Thrown (Range 20/60) · Mastery: Vex"},
  {n:"Javelin", c:"Weapon · Simple Melee", w:2, v:50, d:"1d6 Piercing · Thrown (Range 30/120) · Mastery: Slow"},
  {n:"Light Hammer", c:"Weapon · Simple Melee", w:2, v:200, d:"1d4 Bludgeoning · Light, Thrown (Range 20/60) · Mastery: Nick"},
  {n:"Mace", c:"Weapon · Simple Melee", w:4, v:500, d:"1d6 Bludgeoning · Mastery: Sap"},
  {n:"Quarterstaff", c:"Weapon · Simple Melee", w:4, v:20, d:"1d6 Bludgeoning · Versatile (1d8) · Mastery: Topple"},
  {n:"Sickle", c:"Weapon · Simple Melee", w:2, v:100, d:"1d4 Slashing · Light · Mastery: Nick"},
  {n:"Spear", c:"Weapon · Simple Melee", w:3, v:100, d:"1d6 Piercing · Thrown (Range 20/60), Versatile (1d8) · Mastery: Sap"},
  // ---- Weapon · Simple Ranged ----
  {n:"Dart", c:"Weapon · Simple Ranged", w:0.25, v:5, d:"1d4 Piercing · Finesse, Thrown (Range 20/60) · Mastery: Vex"},
  {n:"Light Crossbow", c:"Weapon · Simple Ranged", w:5, v:2500, d:"1d8 Piercing · Ammunition (Range 80/320; Bolt), Loading, Two-Handed · Mastery: Slow"},
  {n:"Shortbow", c:"Weapon · Simple Ranged", w:2, v:2500, d:"1d6 Piercing · Ammunition (Range 80/320; Arrow), Two-Handed · Mastery: Vex"},
  {n:"Sling", c:"Weapon · Simple Ranged", w:0, v:10, d:"1d4 Bludgeoning · Ammunition (Range 30/120; Bullet) · Mastery: Slow"},
  // ---- Weapon · Martial Melee ----
  {n:"Battleaxe", c:"Weapon · Martial Melee", w:4, v:1000, d:"1d8 Slashing · Versatile (1d10) · Mastery: Topple"},
  {n:"Flail", c:"Weapon · Martial Melee", w:2, v:1000, d:"1d8 Bludgeoning · Mastery: Sap"},
  {n:"Glaive", c:"Weapon · Martial Melee", w:6, v:2000, d:"1d10 Slashing · Heavy, Reach, Two-Handed · Mastery: Graze"},
  {n:"Greataxe", c:"Weapon · Martial Melee", w:7, v:3000, d:"1d12 Slashing · Heavy, Two-Handed · Mastery: Cleave"},
  {n:"Greatsword", c:"Weapon · Martial Melee", w:6, v:5000, d:"2d6 Slashing · Heavy, Two-Handed · Mastery: Graze"},
  {n:"Halberd", c:"Weapon · Martial Melee", w:6, v:2000, d:"1d10 Slashing · Heavy, Reach, Two-Handed · Mastery: Cleave"},
  {n:"Lance", c:"Weapon · Martial Melee", w:6, v:1000, d:"1d10 Piercing · Heavy, Reach, Two-Handed (unless mounted) · Mastery: Topple"},
  {n:"Longsword", c:"Weapon · Martial Melee", w:3, v:1500, d:"1d8 Slashing · Versatile (1d10) · Mastery: Sap"},
  {n:"Maul", c:"Weapon · Martial Melee", w:10, v:1000, d:"2d6 Bludgeoning · Heavy, Two-Handed · Mastery: Topple"},
  {n:"Morningstar", c:"Weapon · Martial Melee", w:4, v:1500, d:"1d8 Piercing · Mastery: Sap"},
  {n:"Pike", c:"Weapon · Martial Melee", w:18, v:500, d:"1d10 Piercing · Heavy, Reach, Two-Handed · Mastery: Push"},
  {n:"Rapier", c:"Weapon · Martial Melee", w:2, v:2500, d:"1d8 Piercing · Finesse · Mastery: Vex"},
  {n:"Scimitar", c:"Weapon · Martial Melee", w:3, v:2500, d:"1d6 Slashing · Finesse, Light · Mastery: Nick"},
  {n:"Shortsword", c:"Weapon · Martial Melee", w:2, v:1000, d:"1d6 Piercing · Finesse, Light · Mastery: Vex"},
  {n:"Trident", c:"Weapon · Martial Melee", w:4, v:500, d:"1d8 Piercing · Thrown (Range 20/60), Versatile (1d10) · Mastery: Topple"},
  {n:"War Pick", c:"Weapon · Martial Melee", w:2, v:500, d:"1d8 Piercing · Versatile (1d10) · Mastery: Sap"},
  {n:"Warhammer", c:"Weapon · Martial Melee", w:5, v:1500, d:"1d8 Bludgeoning · Versatile (1d10) · Mastery: Push"},
  {n:"Whip", c:"Weapon · Martial Melee", w:3, v:200, d:"1d4 Slashing · Finesse, Reach · Mastery: Slow"},
  // ---- Weapon · Martial Ranged ----
  {n:"Blowgun", c:"Weapon · Martial Ranged", w:1, v:1000, d:"1 Piercing · Ammunition (Range 25/100; Needle), Loading · Mastery: Vex"},
  {n:"Hand Crossbow", c:"Weapon · Martial Ranged", w:3, v:7500, d:"1d6 Piercing · Ammunition (Range 30/120; Bolt), Light, Loading · Mastery: Vex"},
  {n:"Heavy Crossbow", c:"Weapon · Martial Ranged", w:18, v:5000, d:"1d10 Piercing · Ammunition (Range 100/400; Bolt), Heavy, Loading, Two-Handed · Mastery: Push"},
  {n:"Longbow", c:"Weapon · Martial Ranged", w:2, v:5000, d:"1d8 Piercing · Ammunition (Range 150/600; Arrow), Heavy, Two-Handed · Mastery: Slow"},
  {n:"Musket", c:"Weapon · Martial Ranged", w:10, v:50000, d:"1d12 Piercing · Ammunition (Range 40/120; Bullet), Loading, Two-Handed · Mastery: Slow"},
  {n:"Pistol", c:"Weapon · Martial Ranged", w:3, v:25000, d:"1d10 Piercing · Ammunition (Range 30/90; Bullet), Loading · Mastery: Vex"},
  // ---- Ammunition ----
  {n:"Arrows (20)", c:"Ammunition", w:1, v:100, d:"Bundle of 20 · stored in a quiver"},
  {n:"Bolts (20)", c:"Ammunition", w:1.5, v:100, d:"Bundle of 20 · stored in a case"},
  {n:"Bullets, Firearm (10)", c:"Ammunition", w:2, v:300, d:"Bundle of 10 · stored in a pouch"},
  {n:"Bullets, Sling (20)", c:"Ammunition", w:1.5, v:4, d:"Bundle of 20 · stored in a pouch"},
  {n:"Needles (50)", c:"Ammunition", w:1, v:100, d:"Bundle of 50 · stored in a pouch"},
  // ---- Armor · Light ----
  {n:"Leather Armor", c:"Armor · Light", w:10, v:1000, d:"AC 11 + Dex modifier"},
  {n:"Padded Armor", c:"Armor · Light", w:8, v:500, d:"AC 11 + Dex modifier · Stealth Disadvantage"},
  {n:"Studded Leather Armor", c:"Armor · Light", w:13, v:4500, d:"AC 12 + Dex modifier"},
  // ---- Armor · Medium ----
  {n:"Breastplate", c:"Armor · Medium", w:20, v:40000, d:"AC 14 + Dex modifier (max 2)"},
  {n:"Chain Shirt", c:"Armor · Medium", w:20, v:5000, d:"AC 13 + Dex modifier (max 2)"},
  {n:"Half Plate Armor", c:"Armor · Medium", w:40, v:75000, d:"AC 15 + Dex modifier (max 2) · Stealth Disadvantage"},
  {n:"Hide Armor", c:"Armor · Medium", w:12, v:1000, d:"AC 12 + Dex modifier (max 2)"},
  {n:"Scale Mail", c:"Armor · Medium", w:45, v:5000, d:"AC 14 + Dex modifier (max 2) · Stealth Disadvantage"},
  // ---- Armor · Heavy ----
  {n:"Chain Mail", c:"Armor · Heavy", w:55, v:7500, d:"AC 16 · Str 13 · Stealth Disadvantage"},
  {n:"Plate Armor", c:"Armor · Heavy", w:65, v:150000, d:"AC 18 · Str 15 · Stealth Disadvantage"},
  {n:"Ring Mail", c:"Armor · Heavy", w:40, v:3000, d:"AC 14 · Stealth Disadvantage"},
  {n:"Splint Armor", c:"Armor · Heavy", w:60, v:20000, d:"AC 17 · Str 15 · Stealth Disadvantage"},
  // ---- Armor · Shield ----
  {n:"Shield", c:"Armor · Shield", w:6, v:1000, d:"AC +2"},
  // ---- Adventuring Gear ----
  {n:"Acid", c:"Adventuring Gear", w:1, v:2500},
  {n:"Alchemist’s Fire", c:"Adventuring Gear", w:1, v:5000},
  {n:"Antitoxin", c:"Adventuring Gear", w:0, v:5000},
  {n:"Backpack", c:"Adventuring Gear", w:5, v:200},
  {n:"Ball Bearings", c:"Adventuring Gear", w:2, v:100},
  {n:"Barrel", c:"Adventuring Gear", w:70, v:200},
  {n:"Basket", c:"Adventuring Gear", w:2, v:40},
  {n:"Bedroll", c:"Adventuring Gear", w:7, v:100},
  {n:"Bell", c:"Adventuring Gear", w:0, v:100},
  {n:"Blanket", c:"Adventuring Gear", w:3, v:50},
  {n:"Block and Tackle", c:"Adventuring Gear", w:5, v:100},
  {n:"Book", c:"Adventuring Gear", w:5, v:2500},
  {n:"Bottle, Glass", c:"Adventuring Gear", w:2, v:200},
  {n:"Bucket", c:"Adventuring Gear", w:2, v:5},
  {n:"Caltrops", c:"Adventuring Gear", w:2, v:100},
  {n:"Candle", c:"Adventuring Gear", w:0, v:1},
  {n:"Case, Crossbow Bolt", c:"Adventuring Gear", w:1, v:100},
  {n:"Case, Map or Scroll", c:"Adventuring Gear", w:1, v:100},
  {n:"Chain", c:"Adventuring Gear", w:10, v:500},
  {n:"Chest", c:"Adventuring Gear", w:25, v:500},
  {n:"Climber’s Kit", c:"Adventuring Gear", w:12, v:2500},
  {n:"Clothes, Fine", c:"Adventuring Gear", w:6, v:1500},
  {n:"Clothes, Traveler’s", c:"Adventuring Gear", w:4, v:200},
  {n:"Component Pouch", c:"Adventuring Gear", w:2, v:2500},
  {n:"Costume", c:"Adventuring Gear", w:4, v:500},
  {n:"Crowbar", c:"Adventuring Gear", w:5, v:200},
  {n:"Flask", c:"Adventuring Gear", w:1, v:2},
  {n:"Grappling Hook", c:"Adventuring Gear", w:4, v:200},
  {n:"Healer’s Kit", c:"Adventuring Gear", w:3, v:500},
  {n:"Holy Water", c:"Adventuring Gear", w:1, v:2500},
  {n:"Hunting Trap", c:"Adventuring Gear", w:25, v:500},
  {n:"Ink", c:"Adventuring Gear", w:0, v:1000},
  {n:"Ink Pen", c:"Adventuring Gear", w:0, v:2},
  {n:"Jug", c:"Adventuring Gear", w:4, v:2},
  {n:"Ladder", c:"Adventuring Gear", w:25, v:10},
  {n:"Lamp", c:"Adventuring Gear", w:1, v:50},
  {n:"Lantern, Bullseye", c:"Adventuring Gear", w:2, v:1000},
  {n:"Lantern, Hooded", c:"Adventuring Gear", w:2, v:500},
  {n:"Lock", c:"Adventuring Gear", w:1, v:1000},
  {n:"Magnifying Glass", c:"Adventuring Gear", w:0, v:10000},
  {n:"Manacles", c:"Adventuring Gear", w:6, v:200},
  {n:"Map", c:"Adventuring Gear", w:0, v:100},
  {n:"Mirror", c:"Adventuring Gear", w:0.5, v:500},
  {n:"Net", c:"Adventuring Gear", w:3, v:100},
  {n:"Oil", c:"Adventuring Gear", w:1, v:10},
  {n:"Paper", c:"Adventuring Gear", w:0, v:20},
  {n:"Parchment", c:"Adventuring Gear", w:0, v:10},
  {n:"Perfume", c:"Adventuring Gear", w:0, v:500},
  {n:"Poison, Basic", c:"Adventuring Gear", w:0, v:10000},
  {n:"Pole", c:"Adventuring Gear", w:7, v:5},
  {n:"Pot, Iron", c:"Adventuring Gear", w:10, v:200},
  {n:"Potion of Healing", c:"Adventuring Gear", w:0.5, v:5000},
  {n:"Pouch", c:"Adventuring Gear", w:1, v:50},
  {n:"Quiver", c:"Adventuring Gear", w:1, v:100},
  {n:"Ram, Portable", c:"Adventuring Gear", w:35, v:400},
  {n:"Rations", c:"Adventuring Gear", w:2, v:50},
  {n:"Robe", c:"Adventuring Gear", w:4, v:100},
  {n:"Rope", c:"Adventuring Gear", w:5, v:100},
  {n:"Sack", c:"Adventuring Gear", w:0.5, v:1},
  {n:"Shovel", c:"Adventuring Gear", w:5, v:200},
  {n:"Signal Whistle", c:"Adventuring Gear", w:0, v:5},
  {n:"Spell Scroll (Cantrip)", c:"Adventuring Gear", w:0, v:3000},
  {n:"Spell Scroll (Level 1)", c:"Adventuring Gear", w:0, v:5000},
  {n:"Spikes, Iron", c:"Adventuring Gear", w:5, v:100},
  {n:"Spyglass", c:"Adventuring Gear", w:1, v:100000},
  {n:"String", c:"Adventuring Gear", w:0, v:10},
  {n:"Tent", c:"Adventuring Gear", w:20, v:200},
  {n:"Tinderbox", c:"Adventuring Gear", w:1, v:50},
  {n:"Torch", c:"Adventuring Gear", w:1, v:1},
  {n:"Vial", c:"Adventuring Gear", w:0, v:100},
  {n:"Waterskin", c:"Adventuring Gear", w:5, v:20, d:"Weight given full"},
  // ---- Equipment Pack ----
  {n:"Burglar’s Pack", c:"Equipment Pack", w:42, v:1600},
  {n:"Diplomat’s Pack", c:"Equipment Pack", w:39, v:3900},
  {n:"Dungeoneer’s Pack", c:"Equipment Pack", w:55, v:1200},
  {n:"Entertainer’s Pack", c:"Equipment Pack", w:58.5, v:4000},
  {n:"Explorer’s Pack", c:"Equipment Pack", w:55, v:1000},
  {n:"Priest’s Pack", c:"Equipment Pack", w:29, v:3300},
  {n:"Scholar’s Pack", c:"Equipment Pack", w:22, v:4000},
  // ---- Tools ----
  {n:"Alchemist’s Supplies", c:"Tools", w:8, v:5000, d:"Intelligence · Identify a substance (DC 15), or start a fire (DC 15)"},
  {n:"Brewer’s Supplies", c:"Tools", w:9, v:2000, d:"Intelligence · Detect poisoned drink (DC 15), or identify alcohol (DC 10)"},
  {n:"Calligrapher’s Supplies", c:"Tools", w:5, v:1000, d:"Dexterity · Write text with impressive flourishes that guard against forgery (DC 15)"},
  {n:"Carpenter’s Tools", c:"Tools", w:6, v:800, d:"Strength · Seal or pry open a door or container (DC 20)"},
  {n:"Cartographer’s Tools", c:"Tools", w:6, v:1500, d:"Wisdom · Draft a map of a small area (DC 15)"},
  {n:"Cobbler’s Tools", c:"Tools", w:5, v:500, d:"Dexterity · Modify footwear to give Advantage on the wearer’s next Dexterity (Acrobatics) check (DC 10)"},
  {n:"Cook’s Utensils", c:"Tools", w:8, v:100, d:"Wisdom · Improve food’s flavor (DC 10), or detect spoiled or poisoned food (DC 15)"},
  {n:"Disguise Kit", c:"Tools", w:3, v:2500, d:"Charisma · Apply makeup (DC 10)"},
  {n:"Forgery Kit", c:"Tools", w:5, v:1500, d:"Dexterity · Mimic 10 or fewer words of someone else’s handwriting (DC 15), or duplicate a wax seal (DC 20)"},
  {n:"Gaming Set: Dice", c:"Tools", w:0, v:10, d:"Wisdom · Discern whether someone is cheating (DC 10), or win the game (DC 20)"},
  {n:"Gaming Set: Dragonchess", c:"Tools", w:0, v:100, d:"Wisdom · Discern whether someone is cheating (DC 10), or win the game (DC 20)"},
  {n:"Gaming Set: Playing cards", c:"Tools", w:0, v:50, d:"Wisdom · Discern whether someone is cheating (DC 10), or win the game (DC 20)"},
  {n:"Gaming Set: Three-dragon ante", c:"Tools", w:0, v:100, d:"Wisdom · Discern whether someone is cheating (DC 10), or win the game (DC 20)"},
  {n:"Glassblower’s Tools", c:"Tools", w:5, v:3000, d:"Intelligence · Discern what a glass object held in the past 24 hours (DC 15)"},
  {n:"Herbalism Kit", c:"Tools", w:3, v:500, d:"Intelligence · Identify a plant (DC 10)"},
  {n:"Jeweler’s Tools", c:"Tools", w:2, v:2500, d:"Intelligence · Discern a gem’s value (DC 15)"},
  {n:"Leatherworker’s Tools", c:"Tools", w:5, v:500, d:"Dexterity · Add a design to a leather item (DC 10)"},
  {n:"Mason’s Tools", c:"Tools", w:8, v:1000, d:"Strength · Chisel a symbol or hole in stone (DC 10)"},
  {n:"Musical Instrument: Bagpipes", c:"Tools", w:6, v:3000, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Drum", c:"Tools", w:3, v:600, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Dulcimer", c:"Tools", w:10, v:2500, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Flute", c:"Tools", w:1, v:200, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Horn", c:"Tools", w:2, v:300, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Lute", c:"Tools", w:2, v:3500, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Lyre", c:"Tools", w:2, v:3000, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Pan flute", c:"Tools", w:2, v:1200, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Shawm", c:"Tools", w:1, v:200, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Musical Instrument: Viol", c:"Tools", w:1, v:3000, d:"Charisma · Play a known tune (DC 10), or improvise a song (DC 15)"},
  {n:"Navigator’s Tools", c:"Tools", w:2, v:2500, d:"Wisdom · Plot a course (DC 10), or determine position by stargazing (DC 15)"},
  {n:"Painter’s Supplies", c:"Tools", w:5, v:1000, d:"Wisdom · Paint a recognizable image of something you’ve seen (DC 10)"},
  {n:"Poisoner’s Kit", c:"Tools", w:2, v:5000, d:"Intelligence · Detect a poisoned object (DC 10)"},
  {n:"Potter’s Tools", c:"Tools", w:3, v:1000, d:"Intelligence · Discern what a ceramic object held in the past 24 hours (DC 15)"},
  {n:"Smith’s Tools", c:"Tools", w:8, v:2000, d:"Strength · Pry open a door or container (DC 20)"},
  {n:"Thieves’ Tools", c:"Tools", w:1, v:2500, d:"Dexterity · Pick a lock (DC 15), or disarm a trap (DC 15)"},
  {n:"Tinker’s Tools", c:"Tools", w:10, v:5000, d:"Dexterity · Assemble a Tiny item composed of scrap, which falls apart in 1 minute (DC 20)"},
  {n:"Weaver’s Tools", c:"Tools", w:5, v:100, d:"Dexterity · Mend a tear in clothing (DC 10), or sew a Tiny design (DC 10)"},
  {n:"Woodcarver’s Tools", c:"Tools", w:5, v:100, d:"Dexterity · Carve a pattern in wood (DC 10)"},
  // ---- Spellcasting Focus ----
  {n:"Arcane Focus: Crystal", c:"Spellcasting Focus", w:1, v:1000},
  {n:"Arcane Focus: Orb", c:"Spellcasting Focus", w:3, v:2000},
  {n:"Arcane Focus: Rod", c:"Spellcasting Focus", w:2, v:1000},
  {n:"Arcane Focus: Staff (also a Quarterstaff)", c:"Spellcasting Focus", w:4, v:500},
  {n:"Arcane Focus: Wand", c:"Spellcasting Focus", w:1, v:1000},
  {n:"Druidic Focus: Sprig of mistletoe", c:"Spellcasting Focus", w:0, v:100},
  {n:"Druidic Focus: Wooden staff (also a Quarterstaff)", c:"Spellcasting Focus", w:4, v:500},
  {n:"Druidic Focus: Yew wand", c:"Spellcasting Focus", w:1, v:1000},
  {n:"Holy Symbol: Amulet (worn or held)", c:"Spellcasting Focus", w:1, v:500},
  {n:"Holy Symbol: Emblem (borne on fabric or a Shield)", c:"Spellcasting Focus", w:0, v:500},
  {n:"Holy Symbol: Reliquary (held)", c:"Spellcasting Focus", w:2, v:500},
  // ---- Mount / Animal ----
  {n:"Camel", c:"Mount / Animal", w:0, v:5000, d:"Carrying capacity 450 lb."},
  {n:"Elephant", c:"Mount / Animal", w:0, v:20000, d:"Carrying capacity 1,320 lb."},
  {n:"Horse, Draft", c:"Mount / Animal", w:0, v:5000, d:"Carrying capacity 540 lb."},
  {n:"Horse, Riding", c:"Mount / Animal", w:0, v:7500, d:"Carrying capacity 480 lb."},
  {n:"Mastiff", c:"Mount / Animal", w:0, v:2500, d:"Carrying capacity 195 lb."},
  {n:"Mule", c:"Mount / Animal", w:0, v:800, d:"Carrying capacity 420 lb."},
  {n:"Pony", c:"Mount / Animal", w:0, v:3000, d:"Carrying capacity 225 lb."},
  {n:"Warhorse", c:"Mount / Animal", w:0, v:40000, d:"Carrying capacity 540 lb."},
  // ---- Tack & Vehicles ----
  {n:"Carriage", c:"Tack & Vehicles", w:600, v:10000},
  {n:"Cart", c:"Tack & Vehicles", w:200, v:1500},
  {n:"Chariot", c:"Tack & Vehicles", w:100, v:25000},
  {n:"Feed per day", c:"Tack & Vehicles", w:10, v:5},
  {n:"Saddle, Exotic", c:"Tack & Vehicles", w:40, v:6000},
  {n:"Saddle, Military", c:"Tack & Vehicles", w:30, v:2000},
  {n:"Saddle, Riding", c:"Tack & Vehicles", w:25, v:1000},
  {n:"Sled", c:"Tack & Vehicles", w:300, v:2000},
  {n:"Stabling per day", c:"Tack & Vehicles", w:0, v:50},
  {n:"Wagon", c:"Tack & Vehicles", w:400, v:3500},
];
